// K2 Sportstyle — product mock data
// Real K2 imagery lifted from GHL CDN (location 95Zi6IzOKrEBwnGxIVYM)
// Placeholder SKUs added to show a populated grid for the prototype.
// On deploy, this is replaced by GHL product feed (or hardcoded with real GHL product IDs).

const GHL_CDN = "https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media";

// Standard kit size range (Unisex Rugby Jersey + Unisex Rugby Short)
const KIT_SIZES = [
  { id: "K4",  label: "K4",  group: "kids", inStock: true },
  { id: "K6",  label: "K6",  group: "kids", inStock: true },
  { id: "K8",  label: "K8",  group: "kids", inStock: true },
  { id: "K10", label: "K10", group: "kids", inStock: true },
  { id: "K12", label: "K12", group: "kids", inStock: true },
  { id: "K14", label: "K14", group: "kids", inStock: true },
  { id: "XS",  label: "XS",  group: "adults", inStock: true },
  { id: "S",   label: "S",   group: "adults", inStock: true },
  { id: "M",   label: "M",   group: "adults", inStock: true },
  { id: "L",   label: "L",   group: "adults", inStock: true },
  { id: "XL",  label: "XL",  group: "adults", inStock: true },
  { id: "2XL", label: "2XL", group: "adults", inStock: true },
  { id: "3XL", label: "3XL", group: "adults", inStock: true },
  { id: "4XL", label: "4XL", group: "adults", inStock: true },
  { id: "5XL", label: "5XL", group: "adults", inStock: true },
  { id: "6XL", label: "6XL", group: "adults", inStock: true },
  { id: "7XL", label: "7XL", group: "adults", inStock: true },
];

// Shorts size chart only goes to 4XL — combo/shirt cover the full 7XL range.
const KIT_FULL_SIZE_IDS  = KIT_SIZES.map(s => s.id);
const KIT_SHORTS_SIZE_IDS = KIT_SIZES.filter(s => !["5XL", "6XL", "7XL"].includes(s.id)).map(s => s.id);

const KIT_BUNDLES = [
  { id: "combo",  label: "Combo · Shirt + Shorts", price: 80, summary: "Full kit — save $10 vs separate", sizeIds: KIT_FULL_SIZE_IDS },
  { id: "shirt",  label: "Shirt only",             price: 45, summary: "Sublimated training jersey",       sizeIds: KIT_FULL_SIZE_IDS },
  { id: "shorts", label: "Shorts only",            price: 45, summary: "Matching training shorts",         sizeIds: KIT_SHORTS_SIZE_IDS },
];

window.K2_PRODUCTS = [
  // ── K² Training Kits (3 colorways, each = jersey + matching shorts) ──
  {
    id: "69fd95cd9f7d31545767a002",
    handle: "k2-training-kit-volt",
    title: "K² Training Kit · Volt",
    collection: "k2-merch",
    collectionLabel: "K2 Merch",
    type: "kit",
    bundles: KIT_BUNDLES,
    sizes: KIT_SIZES,
    images: [
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/fb65da41-eb81-446e-acd8-877b3c86f6f5.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/b1e0fdd2-e1a9-4708-bc31-587ff77b5516.png",
    ],
    badge: "NEW",
    description: "Sublimated training jersey + matching shorts. Volt green chest fade with K² mark and KSQUARED SPORTSTYLE wordmark. Aboriginal-inspired pattern detail through the body. Performance-grade sublimation, 4-way stretch.",
    seoTitle: "K² Training Kit Volt — Member Jersey + Shorts Bundle",
    seoDescription: "Bright volt-on-black K² training kit. Performance jersey plus matching shorts in a member-priced bundle. Designed in Forestville, Sydney.",
    fit: "Athletic. True to size — measurements in size guide.",
    materials: "Sublimated polyester / spandex blend.",
    care: "Cold wash inside out. Hang dry. No iron on print.",
  },
  {
    id: "69fd95e3c23ecf4c5b3bf00e",
    handle: "k2-training-kit-pink",
    title: "K² Training Kit · Hot Pink",
    collection: "k2-merch",
    collectionLabel: "K2 Merch",
    type: "kit",
    bundles: KIT_BUNDLES,
    sizes: KIT_SIZES,
    images: [
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/2fc20109-4dcb-4e6c-9a88-5a61a59e2999.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/fdabdd35-fae1-4d43-b8c0-2407d13e5740.png",
    ],
    badge: "NEW",
    description: "Sublimated training jersey + matching shorts. Hot pink chest fade with K² mark and KSQUARED SPORTSTYLE wordmark. Aboriginal-inspired pattern detail through the body. Performance-grade sublimation, 4-way stretch.",
    seoTitle: "K² Training Kit Hot Pink — Member Jersey + Shorts Bundle",
    seoDescription: "Hot magenta-on-black K² training kit. Performance jersey plus matching shorts at member pricing. K² Sportstyle, designed in Sydney.",
    fit: "Athletic. True to size — measurements in size guide.",
    materials: "Sublimated polyester / spandex blend.",
    care: "Cold wash inside out. Hang dry. No iron on print.",
  },
  {
    id: "69fd95f8c23ecff5ee3bff31",
    handle: "k2-training-kit-sunset",
    title: "K² Training Kit · Sunset",
    collection: "k2-merch",
    collectionLabel: "K2 Merch",
    type: "kit",
    bundles: KIT_BUNDLES,
    sizes: KIT_SIZES,
    images: [
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/85b78308-8c21-4a4d-9d0b-8a4d27327df6.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/9c434e86-c445-4f4a-9a56-3df8795d19fc.png",
    ],
    badge: "NEW",
    description: "Sublimated training jersey + matching shorts. Sunset orange-to-pink fade with K² mark and KSQUARED SPORTSTYLE wordmark. Aboriginal-inspired pattern detail through the body. Performance-grade sublimation, 4-way stretch.",
    seoTitle: "K² Training Kit Sunset — Orange/Pink Member Bundle",
    seoDescription: "Sunset gradient training kit — orange fading through pink to black. Performance jersey plus matching shorts, member-priced bundle. K² Sportstyle, Sydney.",
    fit: "Athletic. True to size — measurements in size guide.",
    materials: "Sublimated polyester / spandex blend.",
    care: "Cold wash inside out. Hang dry. No iron on print.",
  },
  // ── Existing K² merch ──
  {
    id: "69a23a867769897890873f99",
    handle: "k2-bucket-hat",
    title: "K² Bucket Hat",
    collection: "off-the-back-fence",
    collectionLabel: "Off The Back Fence",
    price: 35,
    compareAt: 45,
    images: [
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/969ff0d1-0459-4042-88c3-bda6020f6723.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/1c51a127-d6d3-4899-97c7-f087f558edee.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/6e0e6522-993c-4ca5-959e-ab19de96d63c.png",
    ],
    variants: [
      { id: "v1", name: "Mint / Black / White", inStock: true },
    ],
    badge: "BEST SELLER",
    description: "5-panel bucket hat in heavyweight cotton/poly. White centre panel with embroidered K² mark, mint side panels and underbrim, black crown top and brim trim. Mesh ventilation panels and adjustable cord cinch at back. Black chin strap. Built for the back fence, the BBQ, and the long way home.",
    seoTitle: "K² Bucket Hat — Embroidered 5-Panel Sportstyle Lid | Ksquared",
    seoDescription: "Embroidered 5-panel K² bucket hat in mint, black, and white. Cotton/poly construction with mesh vents, chin strap, and rear cord cinch. Designed in Forestville, Sydney.",
    fit: "Unisex. One size fits most. Rear cord cinch for fine-tuning.",
    materials: "Cotton/poly twill outer. Mesh side ventilation panels.",
    care: "Spot clean. Don't machine wash.",
  },
  {
    id: "69fd96cac23ecfc1e13c7c9d",
    handle: "k2-hoodie",
    title: "K² Heavyweight Hoodie",
    collection: "k2-merch",
    collectionLabel: "K2 Merch",
    price: 90,
    compareAt: 110,
    images: [
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/7bbd0738-6dad-4036-8449-86b1f7809b59.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/168e4d19-402e-414e-a6f2-6a8a0a2234aa.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/b08eb782-845f-4466-914b-a28d620d10e1.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/35be14c0-a387-40b8-8c36-2d65ba6c8505.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/2f033250-301d-4925-bba1-04c7c2a886b3.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/a2bdf7eb-feab-4625-9ef5-32015329d920.png",
    ],
    // Color × Size matrix. PDP renders two pickers (color + size) when every
    // variant has ghlColor + ghlSize; the variant id maps to a single GHL price.
    variants: [
      { id: "bone-s",   name: "Bone — S",   inStock: true, ghlColor: "Bone",  ghlSize: "S"  },
      { id: "bone-m",   name: "Bone — M",   inStock: true, ghlColor: "Bone",  ghlSize: "M"  },
      { id: "bone-l",   name: "Bone — L",   inStock: true, ghlColor: "Bone",  ghlSize: "L"  },
      { id: "bone-xl",  name: "Bone — XL",  inStock: true, ghlColor: "Bone",  ghlSize: "XL" },
      { id: "black-s",  name: "Black — S",  inStock: true, ghlColor: "Black", ghlSize: "S"  },
      { id: "black-m",  name: "Black — M",  inStock: true, ghlColor: "Black", ghlSize: "M"  },
      { id: "black-l",  name: "Black — L",  inStock: true, ghlColor: "Black", ghlSize: "L"  },
      { id: "black-xl", name: "Black — XL", inStock: true, ghlColor: "Black", ghlSize: "XL" },
      { id: "storm-s",  name: "Storm — S",  inStock: true, ghlColor: "Storm", ghlSize: "S"  },
      { id: "storm-m",  name: "Storm — M",  inStock: true, ghlColor: "Storm", ghlSize: "M"  },
      { id: "storm-l",  name: "Storm — L",  inStock: true, ghlColor: "Storm", ghlSize: "L"  },
      { id: "storm-xl", name: "Storm — XL", inStock: true, ghlColor: "Storm", ghlSize: "XL" },
    ],
    badge: null,
    description: "450gsm brushed-back heavyweight hoodie. Drawcord hood, kangaroo pocket. K² mark on chest, KSQUARED SPORTSTYLE balloon-style print across the back. Available in Bone, Black, or Storm grey.",
    seoTitle: "K² Heavyweight Hoodie 450gsm — Bone, Black & Storm | Ksquared",
    seoDescription: "450gsm brushed-back hoodie with K² mark on chest and KSQUARED SPORTSTYLE puff print on the back. Bone, Black, or Storm grey. Member-priced. Designed in Sydney.",
    fit: "Boxy. Size down for a slimmer fit.",
    materials: "85% cotton, 15% polyester. 450gsm brushed-back fleece.",
    care: "Cold wash inside out. Hang dry. No tumble dry. Iron print-side-down on low.",
  },
  {
    id: "6a054791e41b448d757595bd",
    handle: "k2-spray-jacket",
    title: "K² Spray Jacket",
    collection: "k2-merch",
    collectionLabel: "K2 Merch",
    price: 100,
    compareAt: 120,
    images: [
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/850f50f6-aa88-41a9-b940-869ab823527f.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/5e290806-78ac-49ed-b752-6426e1097c9a.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/a48957c9-d0d7-460b-a384-1679a3ea742e.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/a76ec095-6a33-4d0a-943f-9bdae1b3dd48.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/bbde1c34-95d9-4ff1-b4f6-492390be04db.png",
      "https://assets.cdn.filesafe.space/95Zi6IzOKrEBwnGxIVYM/media/3a1f4326-1cd5-4183-afe7-06e8400e21b0.png",
    ],
    variants: [
      { id: "orange-xs",  name: "Orange — XS",  inStock: true, ghlColor: "Orange", ghlSize: "XS"  },
      { id: "orange-s",   name: "Orange — S",   inStock: true, ghlColor: "Orange", ghlSize: "S"   },
      { id: "orange-m",   name: "Orange — M",   inStock: true, ghlColor: "Orange", ghlSize: "M"   },
      { id: "orange-l",   name: "Orange — L",   inStock: true, ghlColor: "Orange", ghlSize: "L"   },
      { id: "orange-xl",  name: "Orange — XL",  inStock: true, ghlColor: "Orange", ghlSize: "XL"  },
      { id: "orange-xxl", name: "Orange — XXL", inStock: true, ghlColor: "Orange", ghlSize: "XXL" },
      { id: "black-xs",   name: "Black — XS",   inStock: true, ghlColor: "Black",  ghlSize: "XS"  },
      { id: "black-s",    name: "Black — S",    inStock: true, ghlColor: "Black",  ghlSize: "S"   },
      { id: "black-m",    name: "Black — M",    inStock: true, ghlColor: "Black",  ghlSize: "M"   },
      { id: "black-l",    name: "Black — L",    inStock: true, ghlColor: "Black",  ghlSize: "L"   },
      { id: "black-xl",   name: "Black — XL",   inStock: true, ghlColor: "Black",  ghlSize: "XL"  },
      { id: "black-xxl",  name: "Black — XXL",  inStock: true, ghlColor: "Black",  ghlSize: "XXL" },
      { id: "mono-xs",    name: "Mono — XS",    inStock: true, ghlColor: "Mono",   ghlSize: "XS"  },
      { id: "mono-s",     name: "Mono — S",     inStock: true, ghlColor: "Mono",   ghlSize: "S"   },
      { id: "mono-m",     name: "Mono — M",     inStock: true, ghlColor: "Mono",   ghlSize: "M"   },
      { id: "mono-l",     name: "Mono — L",     inStock: true, ghlColor: "Mono",   ghlSize: "L"   },
      { id: "mono-xl",    name: "Mono — XL",    inStock: true, ghlColor: "Mono",   ghlSize: "XL"  },
      { id: "mono-xxl",   name: "Mono — XXL",   inStock: true, ghlColor: "Mono",   ghlSize: "XXL" },
    ],
    badge: "NEW",
    description: "Lightweight water-resistant hooded spray jacket. Full-zip front, drawcord hood, elasticated cuffs. Bold K² chevron yoke construction with hot pink trim. Available in Orange (orange yoke, black body), Black (black yoke, orange body), or Mono (white yoke, black body).",
    seoTitle: "K² Spray Jacket — Hooded Full-Zip Sportstyle Jacket | Ksquared",
    seoDescription: "Lightweight water-resistant K² spray jacket with full-zip front and drawcord hood. Three colourways: Orange, Black, Mono. Sizes XS–XXL. Designed in Sydney.",
    fit: "Regular. True to size — sized for layering over a hoodie.",
    materials: "Lightweight water-resistant polyester shell. Mesh-lined for breathability.",
    care: "Cold wash inside out. Hang dry. No tumble dry. No iron on print.",
  },
];

window.K2_COLLECTIONS = [
  { id: "all", label: "All" },
  { id: "k2-merch", label: "K2 Merch" },
  { id: "off-the-back-fence", label: "Off The Back Fence" },
];
